#building vit react app 
FROM node:18-alpine
WORKDIR /app
# Copy package.json and package-lock.json
COPY package.json package-lock.json* ./
RUN npm install

#coping remaning files
COPY . .

#building vite react app 
RUN npm run build

# Copy the build output to the nginx html directory
FROM nginx:alpine

COPY --from=0 /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf


# Start Nginx server port address 
EXPOSE 80


#docker build -t frontend:latest .
CMD ["nginx", "-g", "daemon off;"]